### ISSUE TITLE
[Bug] Two Navigation Actions

### ISSUE THREAD

**Issue by hhergeth** [totu/Swipe2Nav#10]
I have been using the extension successfully on a Windows computer. But on a MacBook there seems to be a bug where nearly every time you swipe it triggers not only one navigation action but two. This happens for both forward and reverse.
From my observations the only time where it does not happen is on pages which take longer to load (but this might just be a coincidence).

On the Review section of the extension page in the store there are also other people reporting the same issue so it is not a machine specific problem.

**Comment by totu** [comment]
You don't need this addon on OSX. Point of this addon was to implement OSX like navigation to Windows Firefox.

**Comment by hhergeth** [comment]
Thanks for letting me know about this!

For all the other MacOS beginners like me: Make sure that System Preferences/Trackpad/Swipe Between Pages is on (for me it was not).
