### ISSUE TITLE
Unintentional navigations when page requires horizontal scrolling

### ISSUE THREAD

**Issue by totu** [totu/Swipe2Nav#2]
If page is wider than screen, i.e. it requires horizontal scrolling the add-on will kick in even though we are not at the edge of the page.

This requires some kind of detector for the edges, so we know when the user actually wants to move backwards/forwards instead of just scroll sideways to view the content.

**Comment by totu** [comment]
Fixed in release 0.1.2

**Comment by rdhar** [comment]
Curiously, I can still observe this issue on v1.0.4 of [SwipeToNavigate](https://addons.mozilla.org/en-US/firefox/addon/swipetonavigate/). I can replicate this using an external mouse and attempting to scroll horizontally with the scroll wheel.

**Comment by totu** [comment]
Hi, @rdhar  

Sadly at the current state this addon is pretty much abandon-ware. I no longer have a Windows machine, so my needs for the addon are non-existent. 

However I will accept a patch if you are wiling to prove one.

**Comment by rdhar** [comment]
Ah, that's a bit of a shame to hear.

It's still one of the best offerings to meet this need on Firefox add-ons. Really appreciate your response!
