### ISSUE TITLE
No longer on addons.mozilla.org

### ISSUE THREAD

**Issue by hackerb9** [totu/Swipe2Nav#7]
Hi! Swipe2Nav looks like just what I want for Firefox, but it is no longer listed at https://addons.mozilla.org/en-US/firefox/addon/touchpadswipelikemac/ . 

Are you going to update it there? If not, how do I go about installing your extension from the github source?

Thanks!

**Comment by totu** [comment]
Swip2Nav was never listed at that URL. You can get it from https://addons.mozilla.org/en-US/firefox/addon/swipetonavigate/
